# Generated by Django 4.2.4 on 2023-08-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hobby", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hobby",
            name="image",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
