# Generated by Django 4.2.4 on 2023-08-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hobby", "0002_alter_hobby_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hobby",
            name="image",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
